# This is a basic workflow to help you get started with Actions

name: Release Upload

#Triggers when any file in the specified dir is touched in the dev branch
on:
  push:
    branches:
      - dev
    paths:
      - 'FtcLib/ReleaseStorage/current/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Upload recent Release
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Most recent .zip release
        # Directory containing files to upload
        path: FtcLib/ReleaseStorage/current
